### ISSUE TITLE
Parts copied with module manager show as missing

### ISSUE THREAD

**Issue by DJKessler** [Sujimichi/Jebretary#1]
Firstly, I really like this project. I think it is a really cool idea, that is well implemented.

However there is a small but annoying issue: ships that have parts which are copied using module manager's "+" feature are listed as having missing parts.

see [Module Manager "Copy" syntax](https://github.com/sarbian/ModuleManager/wiki/Module-Manager-Syntax#copy----or-)

So, if I have the following config file:

```
+PART[mk1pod]
{
    @name = myCopiedmk1pod
    @title = Command Pod Mk1 (Copy)
}
```

![jebretaryissue](https://cloud.githubusercontent.com/assets/7048383/3542072/20e4b54a-0853-11e4-9880-678c92b41b51.JPG)

**Comment by Sujimichi** [comment]
good catch, thanks!! I've not used craft with copied parts so I'd not seen this behaviour before.  I shall modify to account for it.  Would be really helpful if you could either send me a craft file that has that problem, or tell me which mods/parts I need to use to recreate it myself.

**Comment by DJKessler** [comment]
I emailed you a zip that includes everything you'll need to reproduce the issue

**Comment by Sujimichi** [comment]
0.3.4 includes a change that should fix this issue.
