### ISSUE TITLE
(patch) In campaign.rb, nil date makes app crash 

### ISSUE THREAD

**Issue by edvardm** [Sujimichi/Jebretary#2]
I just started using Jebretary (excellent tool :)), and had it crash for some reason to a commit date being nil in campaign.rb. This simple fix gets rid of the issue, though I did not bother to check why it happens.

```
@@ -169,7 +169,7 @@ class Campaign < ActiveRecord::Base
      qs_commit = saves[:quicksave].first if saves[:quicksave]     
      if qs_commit && current_project
        craft_commit = current_project.history(:limit => 1).first
-        t= [[:quicksave, qs_commit], [:current_project, craft_commit]].sort_by{|t, c| c.date}.last
+        t= [[:quicksave, qs_commit], [:current_project, craft_commit]].sort_by{|_, c| c.try(:date) || Time.now}.last
        return t[0]
      else
        return :current_project
```

Update: last patch was barfed, hopefully fixed now. So idea is just to ensure that if commit date is nil for some reason, return something that can be used as comparison (ie. Time.now).

**Comment by Sujimichi** [comment]
well spotted.  This will be fixed in the next version.  Thanks!

**Comment by Sujimichi** [comment]
I'm still not sure why a commit object is missing its date, but I've applied your fix so at least it won't crash the app.
